# Generated by Django 2.2.9 on 2020-08-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0001_initial'),
        ('psicologo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psicologo',
            name='formacao',
        ),
        migrations.AddField(
            model_name='psicologo',
            name='formacao',
            field=models.ManyToManyField(to='formacao.Formacao'),
        ),
    ]
