# Generated by Django 2.2.9 on 2020-08-19 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psicologo', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='psicologo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='psicologo.Psicologo'),
            preserve_default=False,
        ),
    ]
