# Generated by Django 2.2.9 on 2020-08-19 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_psicologo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='psicologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='psicologo.Psicologo'),
        ),
    ]
