# Generated by Django 2.2.9 on 2020-08-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao', models.CharField(max_length=155, verbose_name='Instituição')),
                ('status', models.IntegerField(verbose_name='Status')),
                ('concluido', models.IntegerField(verbose_name='Concluido')),
                ('titulo', models.CharField(max_length=155, verbose_name='Titulo')),
            ],
        ),
    ]
